// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAAy86b0Mwv7uoE0rx1tErhZwaurT7JZs',
    appId: '1:162012907422:web:4133cef0d7484a98a0788f',
    messagingSenderId: '162012907422',
    projectId: 'flutter-lab-firebas-87479',
    authDomain: 'flutter-lab-firebas-87479.firebaseapp.com',
    storageBucket: 'flutter-lab-firebas-87479.appspot.com',
    measurementId: 'G-B2GPQ9P5WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA0ypxEczuZWKEy2Z4TGVM2AxYR3yJWL4',
    appId: '1:162012907422:android:6e71a4f472479afca0788f',
    messagingSenderId: '162012907422',
    projectId: 'flutter-lab-firebas-87479',
    storageBucket: 'flutter-lab-firebas-87479.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_0AZsgB3gvXAOBZ2axh_ITtqD7x3LACc',
    appId: '1:162012907422:ios:db5cabd79bd66330a0788f',
    messagingSenderId: '162012907422',
    projectId: 'flutter-lab-firebas-87479',
    storageBucket: 'flutter-lab-firebas-87479.appspot.com',
    iosClientId:
        '162012907422-gt7glm6mht8etr2m1l78c06ph0ka80f2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_0AZsgB3gvXAOBZ2axh_ITtqD7x3LACc',
    appId: '1:162012907422:ios:db5cabd79bd66330a0788f',
    messagingSenderId: '162012907422',
    projectId: 'flutter-lab-firebas-87479',
    storageBucket: 'flutter-lab-firebas-87479.appspot.com',
    iosClientId:
        '162012907422-gt7glm6mht8etr2m1l78c06ph0ka80f2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );
}
